# Generated by Django 3.0.6 on 2020-05-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsletterrecipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipients',
            name='email',
            field=models.EmailField(default='user@email.com', max_length=254),
            preserve_default=False,
        ),
    ]
